### ISSUE TITLE
Crash on startup in modded instance

### ISSUE THREAD

**Issue by katubug** [Poulpynou/dawnoftimebuilder#32]
Hi, I tried adding your mod to my in-dev modpack to see if it would make a good addition, but I get the following crash: https://gist.github.com/katubug/f3bc1322ceebd4b221410e201aeaa013

I'm not entirely sure what's going on, but this is occurring on Forge 47.2.20 for 1.20.1, using the most recent Dawn of Time version. Thanks for your time!

**Comment by PierreChag** [comment]
Hello,
Thank you for the report, we will investigate this problem !

**Comment by katubug** [comment]
Thank you!

**Comment by PierreChag** [comment]
I can't manage to reproduce this bug. Could you send me your modpack ?

**Comment by katubug** [comment]
Sure thing, it's here:
https://www.mediafire.com/file/yopwjqyjrbw41uu/Cottage_Witch-_Fabled_Wylds-0.29.zip/file

It's a little chaotic at the moment, please pardon the dust

**Comment by PierreChag** [comment]
Hello !
I already found a first bug that comes from DramaticDoor mod. I don't think that's the reason of the bug here (your bug happens before DramaticDoor's bug), but it will definitely crash until this mod has its code fixed.
As a workaround, you can turn off waterlogging in Dramatic Doors config file.

[Here is the issue](https://github.com/Kitteh6660/DramaticDoors/issues/84) I opened in DramaticDoor's repo, if you want to track the progress !

_NB : I'm still trying to find the reason of this bug_

**Comment by katubug** [comment]
Ooh that's very helpful, thank you for the link!

**Comment by PierreChag** [comment]
Could you try to remove DramaticDoor (or setup the config file), and tell me if you still have an error ?

**Comment by katubug** [comment]
I can definitely check tomorrow and let you know!

**Comment by katubug** [comment]
It worked! Disabling waterlogging in Dramatic Doors allows me to load a world with Dawn of Time included in the modpack.
