### ISSUE TITLE
Crashing on Startup in Large Modpack

### ISSUE THREAD

**Issue by megamoth47** [Poulpynou/dawnoftimebuilder#34]
Would love to figure out what is causing the issue.
[crash-2024-03-05_18.10.16-client.txt](https://github.com/DawnOfTimeMC/dawnoftimebuilder/files/14503251/crash-2024-03-05_18.10.16-client.txt)

**Comment by TheGoldenWorld** [comment]
Hi, thanks for your crash report :)
We will dig into your file and see what we can do ! People that mix Create mods and our Builder Edition seems to have a lot of issues

**Comment by PierreChag** [comment]
Hello !
This bug comes from DramaticDoor mod, that doesn't expect doors to work in water, but ours do ! They try to add this feature a second on our doors, which causes a crash ! There is no work around on our side (the only way would be to just remove the waterlog feature).
Until they fix this problem, you can turn off waterlogging in Dramatic Doors config file.

https://github.com/Kitteh6660/DramaticDoors/issues/84 I opened in DramaticDoor's repo, if you want to track the progress !

If you meet another bug, please share the log !
