### ISSUE TITLE
Couch Drops 2

### ISSUE THREAD

**Issue by WenXin20** [Poulpynou/dawnoftimebuilder#39]
```
Minecraft v1.20.1
Dawn of Time v1.3.3
```

The Birch Couch drops 2 when broken

Lattice also has minor z-fighting when placed together. Maybe this can be avoided somehow?
![image](https://github.com/DawnOfTimeMC/dawnoftimebuilder/assets/12000593/14189c1f-13c7-49ab-b9b4-a71c88e9a0e0)

**Comment by PierreChag** [comment]
Hey ! Thank you for the report !
I just fixed the double drop for couch.

Regarding the z-fighting, i can't really fix it without multiplying the number of element in the model by 4. Since it only happens when the player put 2 types of lattice next to each others, I think it's a little bug that can remain in the mod !

If you find any other bug, feel free to create a new ticket to send me a report :)
